

import br.pet.db.PessoaDB;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.text.MaskFormatter;
import minhasclasses.Pessoa;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author vitor
 */
public class TelaCadTutor extends javax.swing.JInternalFrame {

    private String cpfActionPerformed;

    /**
     * Creates new form TelaCadastroTutor
     */
    public TelaCadTutor() {
        initComponents();
        MaskFormatter maskFormatter = null;
        try {
            maskFormatter = new MaskFormatter("##/##/####");
            maskFormatter.setPlaceholderCharacter('_');
            maskFormatter.install(dataNascimentoInputText);
        } catch (ParseException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nomeCompletoInputText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        enderecoInputText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        labelIdade = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cpfInputText = new javax.swing.JFormattedTextField();
        telefoneInputText = new javax.swing.JFormattedTextField();
        botaoSalvar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        botaoProcurar = new javax.swing.JButton();
        localFoto = new javax.swing.JTextField();
        dataNascimentoInputText = new javax.swing.JFormattedTextField();

        setClosable(true);

        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel1.setText("Nome Completo");

        nomeCompletoInputText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeCompletoInputTextActionPerformed(evt);
            }
        });

        jLabel2.setText("CPF");

        jLabel3.setText("Endereço");

        enderecoInputText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enderecoInputTextActionPerformed(evt);
            }
        });

        jLabel4.setText("Data de Nascimento");

        jLabel6.setText("Telefone");

        try {
            cpfInputText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpfInputText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cpfInputTextFocusLost(evt);
            }
        });
        cpfInputText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfInputTextActionPerformed(evt);
            }
        });

        try {
            telefoneInputText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        botaoSalvar.setText("Salvar");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Selecionar Imagem"));

        jLabel7.setText("Foto Cliente");

        botaoProcurar.setText("Procurar");
        botaoProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoProcurarActionPerformed(evt);
            }
        });

        localFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localFotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(botaoProcurar))
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(localFoto)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoProcurar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(localFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        dataNascimentoInputText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dataNascimentoInputTextFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(cpfInputText, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomeCompletoInputText, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                            .addComponent(enderecoInputText)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(labelIdade)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(dataNascimentoInputText, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(telefoneInputText)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(9, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addComponent(botaoSalvar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeCompletoInputText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cpfInputText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enderecoInputText, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telefoneInputText, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(12, 12, 12)
                        .addComponent(dataNascimentoInputText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelIdade)
                        .addGap(34, 34, 34)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(botaoSalvar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoProcurarActionPerformed

      /* JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File ("user.dir"));
        FileNameExtensionFilter filter = new FileNameExtensionFilter ("All Pic", "jpg","png","jpeg","gif");
        
        int a=file.showSaveDialog(null);
        if(a==JFileChooser.APPROVE_OPTION){
            jTextField2.setText(file.getSelectedFile().getAbsolutePath());
        }
        */
      JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File ("user.dir"));

        FileNameExtensionFilter filter = new FileNameExtensionFilter ("All Pic", "jpg","png","jpeg","gif");

        int a=file.showSaveDialog(null);
        if(a==JFileChooser.APPROVE_OPTION){
            localFoto.setText(file.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_botaoProcurarActionPerformed

    private void cpfInputTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfInputTextActionPerformed
        
    
    }//GEN-LAST:event_cpfInputTextActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        try {
    JOptionPane.showMessageDialog(rootPane,"Realizando cadastro...");
    Pessoa pessoa = new Pessoa();
    pessoa.setNome(nomeCompletoInputText.getText());
    pessoa.setEndereco(enderecoInputText.getText());
    pessoa.setCpf(cpfInputText.getText());
    String nascimento = dataNascimentoInputText.getText();
    SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
    Date date = dateFormat.parse(nascimento);
    LocalDate localDate = date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
    pessoa.setNascimento(localDate);
    System.out.println(pessoa);
    PessoaDB pessoadb = new PessoaDB();
    pessoadb.salvar(pessoa);
} catch (ParseException ex) {
    Logger.getLogger(TelaCadTutor.class.getName()).log(Level.SEVERE, null, ex);
} catch (ClassNotFoundException ex) {
    Logger.getLogger(TelaCadTutor.class.getName()).log(Level.SEVERE, null, ex);
}

String cpf = cpfInputText.getText().replaceAll("\\D+", "");
String nomeArquivo = cpf + ".txt";
File arquivo = new File(nomeArquivo);

try {
    // Verificar se o arquivo já existe
    if (!arquivo.exists()) {
        arquivo.createNewFile();
    }

    // Escrever as informações no arquivo
    FileWriter writer = new FileWriter(arquivo);
    writer.write("Nome Completo do Tutor: " + nomeCompletoInputText.getText() + "\n");
    writer.write("Endereço: " + enderecoInputText.getText() + "\n");
    writer.write("CPF: " + cpfInputText.getText() + "\n");
    writer.write("Telefone: " + telefoneInputText.getText() + "\n");
    // Escrever as demais informações...

    writer.close();

    JOptionPane.showMessageDialog(this, "Dados salvos com sucesso!");

} catch (IOException ex) {
    ex.printStackTrace();
    JOptionPane.showMessageDialog(this, "Erro ao salvar os dados.");
}
    
    
    String caminhoFoto = localFoto.getText();
    

    if (!caminhoFoto.isEmpty()) {
        File foto = new File(caminhoFoto);
        caminhoFoto = cpfInputText.getText().replaceAll("\\D+", "") + ".txt";
        String destino = "logo";

    try {
        // Copia o arquivo para a pasta "logo" dentro do projeto com o nome do CPF
        Files.copy(foto.toPath(), new File(destino, cpf + ".jpg").toPath(), StandardCopyOption.REPLACE_EXISTING);
        System.out.println("Foto salva em: " + destino);
    } catch (IOException e) {
        e.printStackTrace();
    }
}






        
    
     
    
    



        
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void cpfInputTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cpfInputTextFocusLost
        boolean valido = Pessoa.isCPFValido(cpfInputText.getText());
        if (!valido){
         JOptionPane.showMessageDialog(rootPane,"CPF inválido!");   
        }
        
    }//GEN-LAST:event_cpfInputTextFocusLost

    private void dataNascimentoInputTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataNascimentoInputTextFocusLost
       String dataNascimento = dataNascimentoInputText.getText();
       SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            try {
                Date date = dateFormat.parse(dataNascimento);
                LocalDate localDate = date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
                int idade = Pessoa.calcularIdade(localDate);
                labelIdade.setText("Sua idade é: " +idade);
                if(idade >120){
                    labelIdade.setText("Informe outra data de nascimento");
                }
                
            } catch (ParseException ex) {
                System.out.println("Data inválida");
            }
    }//GEN-LAST:event_dataNascimentoInputTextFocusLost

    private void localFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localFotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_localFotoActionPerformed

    private void nomeCompletoInputTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeCompletoInputTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeCompletoInputTextActionPerformed

    private void enderecoInputTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enderecoInputTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enderecoInputTextActionPerformed
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoProcurar;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JFormattedTextField cpfInputText;
    private javax.swing.JFormattedTextField dataNascimentoInputText;
    private javax.swing.JTextField enderecoInputText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelIdade;
    private javax.swing.JTextField localFoto;
    private javax.swing.JTextField nomeCompletoInputText;
    private javax.swing.JFormattedTextField telefoneInputText;
    // End of variables declaration//GEN-END:variables
}
